<?php
session_start();

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'Admin') {
    die("Access Denied");
}

$host = "localhost";
$user = "root";
$password = "";
$database = "freelance_platform";

$conn = new mysqli($host, $user, $password, $database);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$usersQuery = "SELECT id, name, email, role, is_verified FROM Users ORDER BY id DESC";
$usersResult = $conn->query($usersQuery);

if (!$usersResult) {
    die("Query failed: " . $conn->error);
}
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Users Report - FreelanceHub</title>
    <style>
    @media print {
        .no-print {
            display: none;
        }

        body {
            margin: 0;
            padding: 20px;
        }

        .page-break {
            page-break-before: always;
        }
    }

    body {
        font-family: 'Segoe UI', Arial, sans-serif;
        margin: 0;
        padding: 20px;
        background: white;
    }

    .report-container {
        max-width: 1200px;
        margin: 0 auto;
        background: white;
    }

    .header {
        text-align: center;
        margin-bottom: 30px;
        padding-bottom: 20px;
        border-bottom: 3px solid #e8a045;
    }

    .header h1 {
        color: #1a1a2e;
        margin: 0 0 10px 0;
        font-size: 28px;
    }

    .header p {
        color: #6c757d;
        margin: 5px 0;
        font-size: 14px;
    }

    .company-info {
        text-align: center;
        margin-bottom: 20px;
    }

    .company-info h2 {
        color: #1a1a2e;
        margin: 0;
        font-size: 20px;
    }

    .report-info {
        display: flex;
        justify-content: space-between;
        margin-bottom: 30px;
        padding: 15px;
        background: #f8f9fa;
        border-radius: 8px;
    }

    .report-info p {
        margin: 5px 0;
        font-size: 12px;
        color: #495057;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th {
        background: #1a1a2e;
        color: white;
        padding: 12px;
        text-align: left;
        font-weight: 600;
        font-size: 13px;
    }

    td {
        padding: 10px 12px;
        border-bottom: 1px solid #dee2e6;
        font-size: 13px;
        color: #212529;
    }

    tr:hover {
        background: #f8f9fa;
    }

    .footer {
        margin-top: 40px;
        padding-top: 20px;
        text-align: center;
        border-top: 1px solid #dee2e6;
        font-size: 11px;
        color: #6c757d;
    }

    .badge {
        display: inline-block;
        padding: 3px 8px;
        border-radius: 20px;
        font-size: 11px;
        font-weight: 600;
    }

    .badge-client {
        background: rgba(26, 26, 46, 0.1);
        color: #1a1a2e;
    }

    .badge-freelancer {
        background: rgba(232, 160, 69, 0.2);
        color: #d35400;
    }

    .badge-admin {
        background: rgba(231, 76, 60, 0.15);
        color: #c0392b;
    }

    .badge-verified {
        background: #d4edda;
        color: #155724;
    }

    .badge-not-verified {
        background: #f8d7da;
        color: #721c24;
    }

    .btn-print {
        background: #1a1a2e;
        color: white;
        border: none;
        padding: 10px 25px;
        border-radius: 6px;
        font-size: 14px;
        cursor: pointer;
        margin-bottom: 20px;
    }

    .btn-print:hover {
        background: #e8a045;
        color: #1a1a2e;
    }

    .summary-box {
        display: flex;
        gap: 20px;
        margin-bottom: 30px;
    }

    .summary-card {
        flex: 1;
        background: #f8f9fa;
        padding: 15px;
        border-radius: 8px;
        text-align: center;
    }

    .summary-card h3 {
        margin: 0 0 5px 0;
        font-size: 24px;
        color: #1a1a2e;
    }

    .summary-card p {
        margin: 0;
        font-size: 12px;
        color: #6c757d;
    }
    </style>
</head>

<body>
    <div class="report-container">
        <button onclick="window.print()" class="btn-print no-print"
            style="position: fixed; top: 20px; right: 20px; z-index: 1000;">
            <i class="bi bi-printer"></i> Save as PDF
        </button>

        <div class="header">
            <h1>📊 FreelanceHub Platform</h1>
            <h2>Users Report</h2>
            <p>Complete list of all registered users</p>
        </div>

        <div class="report-info">
            <div>
                <p><strong>Report Generated:</strong> <?php echo date('F d, Y h:i:s A'); ?></p>
                <p><strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['username'] ?? 'Admin'); ?></p>
            </div>
            <div>
                <p><strong>Report ID:</strong> #<?php echo time(); ?></p>
                <p><strong>Status:</strong> Official Report</p>
            </div>
        </div>

        <?php
        $totalUsers = $usersResult->num_rows;
        $freelancerCount = 0;
        $clientCount = 0;
        $adminCount = 0;
        $verifiedCount = 0;

        $usersResult->data_seek(0);
        while ($row = $usersResult->fetch_assoc()) {
            if ($row['role'] == 'Freelancer') $freelancerCount++;
            elseif ($row['role'] == 'Client') $clientCount++;
            else $adminCount++;
            if ($row['is_verified']) $verifiedCount++;
        }
        $usersResult->data_seek(0);
        ?>

        <div class="summary-box">
            <div class="summary-card">
                <h3><?php echo $totalUsers; ?></h3>
                <p>Total Users</p>
            </div>
            <div class="summary-card">
                <h3><?php echo $clientCount; ?></h3>
                <p>Clients</p>
            </div>
            <div class="summary-card">
                <h3><?php echo $freelancerCount; ?></h3>
                <p>Freelancers</p>
            </div>
            <div class="summary-card">
                <h3><?php echo $adminCount; ?></h3>
                <p>Admins</p>
            </div>
            <div class="summary-card">
                <h3><?php echo $verifiedCount; ?></h3>
                <p>Verified Users</p>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if ($usersResult->num_rows > 0) {
                    while ($row = $usersResult->fetch_assoc()) {
                        $verified = $row['is_verified'] ? '<span class="badge badge-verified">Verified</span>' : '<span class="badge badge-not-verified">Not Verified</span>';

                        $roleClass = '';
                        if ($row['role'] == 'Client') {
                            $roleClass = 'badge-client';
                        } elseif ($row['role'] == 'Freelancer') {
                            $roleClass = 'badge-freelancer';
                        } else {
                            $roleClass = 'badge-admin';
                        }

                        echo '<tr>
                            <td>' . $row['id'] . '</td>
                            <td><strong>' . htmlspecialchars($row['name']) . '</strong></td>
                            <td>' . htmlspecialchars($row['email']) . '</td>
                            <td><span class="badge ' . $roleClass . '">' . $row['role'] . '</span></td>
                            <td>' . $verified . '</td>
                        </tr>';
                    }
                } else {
                    echo '<tr><td colspan="5" style="text-align:center">No users found</td></tr>';
                }
                ?>
            </tbody>
        </table>

        <div class="footer">
            <p>FreelanceHub Platform - Official Users Report</p>
            <p>This report is system generated and does not require signature</p>
            <p>© <?php echo date('Y'); ?> FreelanceHub. All rights reserved.</p>
        </div>
    </div>

    <script>
    function downloadPDF() {
        window.print();
    }
    </script>
</body>

</html>

<?php
$conn->close();
?>